# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
variable "lambda_layers_bucket_arn" {
  description = "ARN of the S3 bucket for storing Lambda layers. If not provided, a new bucket will be created."
  type        = string
  default     = ""
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources in the document processing workflow"
  type        = string
  default     = null
}

variable "enable_encryption" {
  description = "Whether encryption is enabled. Use this instead of checking encryption_key_arn != null to avoid unknown value issues in for_each/count."
  type        = bool
  default     = false
}

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}


variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results will be stored"
  type        = string
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for temporary storage during document processing"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the optional DynamoDB table for storing configuration settings"
  type        = string
  default     = null
}

variable "api" {
  description = "Optional GraphQL API that is used to track processing status and results of documents"
  type = object({
    api_id           = string
    api_name         = optional(string)
    api_arn          = string
    graphql_url      = string
    realtime_url     = optional(string)
    api_key          = optional(string)
    lambda_functions = optional(any)
  })
  default = null
}

variable "tracking_table_arn" {
  description = "ARN of the optional document tracking table"
  type        = string
  default     = null
}

variable "concurrency_table_arn" {
  description = "ARN of the table that manages concurrency limits for document processing"
  type        = string
  default     = null
}

variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer to use for functions that require idp_common"
  type        = string
}

variable "data_tracking_retention_days" {
  description = "The retention period for document tracking data in days"
  type        = number
  default     = 365
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by the document processing components in days"
  type        = number
  default     = 7
  validation {
    condition     = contains([1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653], var.log_retention_days)
    error_message = "Log retention days must be one of the allowed values."
  }
}

variable "log_level" {
  description = "The log level for the document processing components"
  type        = string
  default     = "INFO"
  validation {
    condition     = contains(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], var.log_level)
    error_message = "Allowed values for log_level are \"DEBUG\", \"INFO\", \"WARNING\", \"ERROR\", or \"CRITICAL\"."
  }
}

variable "subnet_ids" {
  description = "List of subnet IDs for Lambda functions to run in"
  type        = list(string)
  default     = []
}

variable "security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

variable "evaluation_config" {
  description = "Optional evaluation configuration for document processing quality assessment"
  type = object({
    baseline_bucket_arn  = string
    evaluation_model_arn = string
  })
  default = null
}

variable "enable_reporting" {
  description = "Whether to enable the reporting environment for analytics and evaluation capabilities"
  type        = bool
  default     = false
}

variable "reporting_bucket_arn" {
  description = "ARN of the S3 bucket for reporting data (required when enable_reporting is true)"
  type        = string
  default     = null
}

variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
  validation {
    condition     = contains(["Active", "PassThrough"], var.lambda_tracing_mode)
    error_message = "Lambda tracing mode must be either 'Active' or 'PassThrough'."
  }
}
