# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Public variable surface for the BDA processor façade.
#
# This surface is intentionally preserved so the root `module.bda_processor`
# call still type-checks. Pattern-specific document processing is delegated to
# the shared engine (`module "engine"` -> ../unified-processor); most of these
# variables are forwarded straight through.

variable "name" {
  description = "Name for the BDA processor resources"
  type        = string
  default     = "bda-processor"
}

# Retained for root call compatibility. The former monolith used this bucket to
# stage CodeBuild Docker-image sources; the shared engine builds Lambdas from
# zip archives and no longer needs it. Kept so the root call type-checks.
variable "lambda_layers_bucket_arn" {
  description = "ARN of the S3 bucket for storing Lambda layers (retained for root-call compatibility; unused by the façade — the shared engine packages Lambdas from zip archives)."
  type        = string
  default     = ""
}

# API wiring
variable "enable_api" {
  description = "Whether the API is enabled. Use this instead of checking api_id != null to avoid unknown value issues in count."
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

# Shared environment ARNs
variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

# Processing environment configuration
variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

# Encryption
variable "enable_encryption" {
  description = "Whether encryption is enabled. Use this instead of checking encryption_key_arn != null to avoid unknown value issues in count."
  type        = bool
  default     = false
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources in the document processing workflow"
  type        = string
  default     = null
}

# VPC configuration
variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions to run in"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

# Layers
variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer containing shared utilities"
  type        = string
}

variable "base_layer_arn" {
  description = "ARN of the shared base Lambda layer (idp_common with docs_service extras, v0.4.11+)."
  type        = string
  default     = null
}

variable "evaluation_layer_arn" {
  description = "ARN of the dedicated evaluation Lambda layer (idp_common with evaluation extras). Forwarded to the engine; required by the engine when evaluation is enabled."
  type        = string
  default     = null
}

# BDA-specific (pattern-specific) input.
variable "data_automation_project_arn" {
  description = "The ARN of the Bedrock Data Automation Project used for document processing. Consumer-supplied; the project id is exposed as an output and the ARN is used to link configuration versions to the BDA branch via seeding (not a deploy-time engine input)."
  type        = string
}

# Evaluation configuration
variable "evaluation_model_id" {
  description = "Optional model used for evaluating extraction results. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "evaluation_baseline_bucket_name" {
  description = "Name of the S3 bucket containing baseline documents for evaluation. Leave empty to skip evaluation."
  type        = string
  default     = ""
}

# Summarization configuration
variable "summarization_model_id" {
  description = "Optional model used for document summarization. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "summarization_guardrail" {
  description = "Optional Bedrock guardrail to apply to summarization model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

# Document processing configuration
variable "config" {
  description = "Configuration values from config_library YAML files"
  type        = any
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

variable "additional_configurations" {
  description = "Extra non-active, editable configuration versions seeded alongside the default (version_name => config object). Shown in the UI version dropdown."
  type        = any
  default     = {}
}

variable "seed_managed_configs" {
  description = "Seed the managed baseline configuration versions as non-active reference rows."
  type        = bool
  default     = true
}
