# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0

variable "lambda_layers_bucket_arn" {
  description = "ARN of the S3 bucket for storing Lambda layers. If not provided, a new bucket will be created."
  type        = string
  default     = ""
}

variable "name" {
  description = "Name for the BDA processor resources"
  type        = string
  default     = "bda-processor"
}

# New flattened variables
variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

variable "bda_metadata_table_arn" {
  description = "ARN of the DynamoDB table that stores BDA processing metadata (optional, required for HITL functionality)"
  type        = string
  default     = null
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources in the document processing workflow"
  type        = string
  default     = null
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions to run in"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}



variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
}



variable "data_automation_project_arn" {
  description = "The ARN of the Bedrock Data Automation Project used for document processing"
  type        = string
}


variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer containing shared utilities"
  type        = string
}

variable "evaluation_model_id" {
  description = "Optional model used for evaluating extraction results. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "summarization_model_id" {
  description = "Optional model used for document summarization. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "summarization_guardrail" {
  description = "Optional Bedrock guardrail to apply to summarization model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}



variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

variable "config" {
  description = "Configuration values from config_library YAML files"
  type        = any
}

variable "vpc_config" {
  description = "VPC configuration for Lambda functions"
  type = object({
    subnet_ids         = list(string)
    security_group_ids = list(string)
  })
  default = null
}

variable "tags" {
  description = "Tags to apply to resources"
  type        = map(string)
  default     = {}
}

# HITL-related variables
variable "sagemaker_a2i_review_portal_url" {
  description = "URL for the SageMaker A2I review portal"
  type        = string
  default     = null
}

variable "hitl_workteam_arn" {
  description = "ARN of the SageMaker workteam for HITL"
  type        = string
  default     = null
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "enable_ecr_image_scanning" {
  description = "Enable ECR vulnerability scanning on image push for the BDA processor Lambda images"
  type        = bool
  default     = false
}

variable "evaluation_baseline_bucket_name" {
  description = "Name of the S3 bucket containing baseline documents for evaluation. Leave empty to skip evaluation."
  type        = string
  default     = ""
}

variable "reporting_bucket_name" {
  description = "Name of the S3 bucket for storing evaluation reporting data."
  type        = string
  default     = ""
}

variable "save_reporting_function_name" {
  description = "Name of the Lambda function that saves evaluation results to the reporting bucket."
  type        = string
  default     = ""
}
