# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Variables for SageMaker UDOP Processor

variable "name" {
  description = "Name prefix for all resources"
  type        = string
}

# Flat variables for processing environment resources
variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
  default     = null
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
  default     = null
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
  default     = null
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "enable_api" {
  description = "Whether the API is enabled"
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources"
  type        = string
  default     = null
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
  default     = null
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
  default     = null
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

variable "classification_endpoint_arn" {
  description = "ARN of the SageMaker endpoint for document classification"
  type        = string
}

variable "extraction_model_id" {
  description = "Optional model ID for information extraction. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "extraction_guardrail" {
  description = "Optional Bedrock guardrail to apply to extraction model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "summarization_model_id" {
  description = "Optional model ID for document summarization. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "summarization_guardrail" {
  description = "Optional Bedrock guardrail to apply to summarization model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "evaluation_model_id" {
  description = "Optional model ID for evaluating extraction results. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "ocr_max_workers" {
  description = "Maximum number of concurrent workers for OCR processing"
  type        = number
  default     = 20
}

variable "classification_max_workers" {
  description = "Maximum number of concurrent workers for classification processing"
  type        = number
  default     = 20
}

variable "classification_guardrail" {
  description = "Optional guardrail configuration for classification function"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "config" {
  description = "Configuration to override defaults"
  type        = any
  default     = null
}

variable "idp_common_layer_arn" {
  description = "ARN of the IDP common layer"
  type        = string
}



variable "assessment_model_id" {
  description = "The Bedrock model ID to use for assessment (when assessment is enabled)"
  type        = string
  default     = "anthropic.claude-3-haiku-20240307-v1:0"
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default     = {}
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}
