# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
# Variables for the SageMaker-UDOP processor façade (Pattern 3 retained).
#
# This is the public input surface. Pattern-specific fields (the consumer-
# supplied SageMaker endpoint) drive the engine's native SageMaker classification
# backend; all other fields are forwarded to the shared engine (`module.engine`).

variable "name" {
  description = "Name prefix for all resources"
  type        = string
}

# =============================================================================
# Pattern-specific: consumer-supplied SageMaker endpoint
# =============================================================================

variable "classification_endpoint_arn" {
  description = "ARN of the consumer-supplied SageMaker endpoint used for document classification. The façade provisions NO SageMaker hosting/training; it grants the classification Lambda sagemaker:InvokeEndpoint on this endpoint and passes its name as SAGEMAKER_ENDPOINT_NAME."
  type        = string
}

# =============================================================================
# Shared environment ARNs (forwarded to the engine)
# =============================================================================

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
  default     = null
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
  default     = null
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
  default     = null
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
  default     = null
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "enable_api" {
  description = "Whether the API is enabled"
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources"
  type        = string
  default     = null
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
  default     = null
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
  default     = null
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

# =============================================================================
# Model configuration (forwarded to the engine)
# =============================================================================

variable "extraction_model_id" {
  description = "Optional model ID for information extraction. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "summarization_model_id" {
  description = "Optional model ID for document summarization. If not provided, summarization is disabled."
  type        = string
  default     = null
}

variable "evaluation_model_id" {
  description = "Optional model ID for evaluating extraction results. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "ocr_max_workers" {
  description = "Maximum number of concurrent workers for OCR processing"
  type        = number
  default     = 20
}

variable "classification_max_workers" {
  description = "Maximum number of concurrent workers for classification processing"
  type        = number
  default     = 20
}

variable "config" {
  description = "Document processing configuration (from config_library YAML), forwarded to the engine."
  type        = any
  default     = null
}

variable "idp_common_layer_arn" {
  description = "ARN of the IDP common layer"
  type        = string
}

variable "base_layer_arn" {
  description = "ARN of the shared base Lambda layer (v0.4.11+), forwarded to the engine."
  type        = string
  default     = null
}

variable "evaluation_layer_arn" {
  description = "ARN of the dedicated evaluation Lambda layer (idp_common with evaluation+docs_service extras). Required when evaluation is enabled."
  type        = string
  default     = null
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default     = {}
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "evaluation_baseline_bucket_name" {
  description = "Name of the S3 bucket containing baseline documents for evaluation. Leave empty to skip evaluation."
  type        = string
  default     = ""
}
