# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
variable "name" {
  description = "Name prefix for resources"
  type        = string
}

# New flattened variables
variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for storing intermediate processing artifacts"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}


variable "document_queue_arn" {
  description = "ARN of the SQS queue that holds documents waiting to be processed"
  type        = string
}

variable "queue_sender_function_name" {
  description = "Name of the Lambda function that sends documents to the processing queue"
  type        = string
}

variable "queue_sender_function_arn" {
  description = "ARN of the Lambda function that sends documents to the processing queue"
  type        = string
}

variable "workflow_tracker_function_name" {
  description = "Name of the Lambda function that tracks workflow execution status"
  type        = string
}

variable "workflow_tracker_function_arn" {
  description = "ARN of the Lambda function that tracks workflow execution status"
  type        = string
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources in the document processing workflow"
  type        = string
  default     = null
}

variable "enable_encryption" {
  description = "Whether encryption is enabled. Use this instead of checking encryption_key_arn != null to avoid unknown value issues in for_each/count."
  type        = bool
  default     = false
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for Lambda functions to run in"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for Lambda functions"
  type        = list(string)
  default     = []
}

variable "processor" {
  description = "Processor configuration"
  type = object({
    state_machine_arn          = string
    max_processing_concurrency = number
  })
}

variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer to use for functions that require idp_common"
  type        = string
}

variable "evaluation_options" {
  description = "Optional evaluation configuration"
  type = object({
    baseline_bucket_arn = string
    model_id            = string
  })
  default = null
}

variable "s3_prefix" {
  description = "Optional S3 prefix to filter documents for processing"
  type        = string
  default     = null
}

variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"

  validation {
    condition     = contains(["Active", "PassThrough"], var.lambda_tracing_mode)
    error_message = "lambda_tracing_mode must be either 'Active' or 'PassThrough'."
  }
}
