# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
variable "region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "prefix" {
  description = "Prefix to add to resource names"
  type        = string
  default     = "idp"
}

# User Identity Configuration
variable "admin_email" {
  description = "Optional email address for the admin user. If provided, an admin user will be created in the Cognito User Pool."
  type        = string
  default     = null
}

variable "log_level" {
  description = "The log level for the document processing components"
  type        = string
  default     = "INFO"
  validation {
    condition     = contains(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], var.log_level)
    error_message = "Allowed values for log_level are \"DEBUG\", \"INFO\", \"WARNING\", \"ERROR\", or \"CRITICAL\"."
  }
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by the document processing components in days"
  type        = number
  default     = 7
  validation {
    condition     = contains([1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653], var.log_retention_days)
    error_message = "Log retention days must be one of the allowed values."
  }
}

variable "data_tracking_retention_days" {
  description = "The retention period for document tracking data in days"
  type        = number
  default     = 365
}

# Feature flags
variable "enable_api" {
  description = "Enable GraphQL API for programmatic access and notifications"
  type        = bool
  default     = true
}

variable "web_ui" {
  description = "Web UI configuration object"
  type = object({
    enabled                    = optional(bool, true)
    create_infrastructure      = optional(bool, true)
    bucket_name                = optional(string, null)
    cloudfront_distribution_id = optional(string, null)
    logging_enabled            = optional(bool, false)
    logging_bucket_arn         = optional(string, null)
    enable_signup              = optional(string, "")
  })
  default = {
    enabled                    = true
    create_infrastructure      = true
    bucket_name                = null
    cloudfront_distribution_id = null
    logging_enabled            = false
    logging_bucket_arn         = null
    enable_signup              = ""
  }
}

variable "enable_evaluation" {
  description = "Enable evaluation functionality (simplified flag)"
  type        = bool
  default     = false
}

variable "evaluation_model_id" {
  description = "Model ID for evaluation processing"
  type        = string
  default     = "anthropic.claude-3-sonnet-20240229-v1:0"
}

# Reporting Configuration
variable "enable_reporting" {
  description = "Enable reporting functionality (simplified flag)"
  type        = bool
  default     = false
}

# Agent Analytics Configuration
variable "agent_analytics" {
  description = "Configuration for agent analytics functionality"
  type = object({
    enabled  = optional(bool, false)
    model_id = optional(string, "us.anthropic.claude-3-5-sonnet-20241022-v2:0")
  })
  default = { enabled = false }

  validation {
    condition     = !var.agent_analytics.enabled || var.agent_analytics.model_id != null
    error_message = "When agent_analytics.enabled is true, model_id must be provided."
  }
}

# Discovery Configuration
variable "discovery" {
  description = "Configuration for document discovery functionality"
  type = object({
    enabled = optional(bool, false)
  })
  default = { enabled = false }
}

# Chat with Document Configuration
variable "chat_with_document" {
  description = "Configuration for chat with document functionality"
  type = object({
    enabled                  = optional(bool, false)
    guardrail_id_and_version = optional(string, null)
  })
  default = { enabled = false }
}

# Model Configuration
variable "classification_model_id" {
  description = "Model ID for document classification (Bedrock LLM processor only)"
  type        = string
  default     = "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
}

variable "extraction_model_id" {
  description = "Model ID for information extraction (Bedrock LLM processor only)"
  type        = string
  default     = "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
}

variable "summarization_enabled" {
  description = "Enable document summarization for Bedrock LLM processor"
  type        = bool
  default     = true
}

variable "summarization_model_id" {
  description = "Model ID for document summarization"
  type        = string
  default     = "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
}

variable "enable_assessment" {
  description = "Enable assessment functionality"
  type        = bool
  default     = false
}

variable "enable_hitl" {
  description = "Enable Human-in-the-Loop (HITL) functionality for document review"
  type        = bool
  default     = false
}

# Configuration File Path
variable "config_file_path" {
  description = "Path to the configuration YAML file for document processing"
  type        = string
  default     = "../../sources/config_library/pattern-2/lending-package-sample/config.yaml"
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default     = {}
}
