# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
variable "name" {
  description = "Name for the Bedrock LLM processor resources"
  type        = string
  default     = "bedrock-llm-processor"
}

# Flat variables for processing environment resources - ARNs only
variable "enable_api" {
  description = "Whether the API is enabled"
  type        = bool
  default     = false
}

variable "api_id" {
  description = "ID of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_arn" {
  description = "ARN of the GraphQL API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "api_graphql_url" {
  description = "GraphQL URL of the API that provides interfaces for querying document status and metadata"
  type        = string
  default     = null
}

variable "input_bucket_arn" {
  description = "ARN of the S3 bucket where source documents to be processed are stored"
  type        = string
}

variable "output_bucket_arn" {
  description = "ARN of the S3 bucket where processed documents and extraction results are stored"
  type        = string
}

variable "working_bucket_arn" {
  description = "ARN of the S3 bucket used for temporary processing files"
  type        = string
}

variable "configuration_table_arn" {
  description = "ARN of the DynamoDB table that stores configuration settings"
  type        = string
}

variable "tracking_table_arn" {
  description = "ARN of the DynamoDB table that tracks document processing status and metadata"
  type        = string
}

variable "concurrency_table_arn" {
  description = "ARN of the DynamoDB table that manages concurrency limits for document processing"
  type        = string
}

variable "metric_namespace" {
  description = "The namespace for CloudWatch metrics emitted by the document processing system"
  type        = string
}

variable "log_level" {
  description = "The log level for document processing components"
  type        = string
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key used for encrypting resources"
  type        = string
  default     = null
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by document processing components"
  type        = number
  default     = 7
}

variable "vpc_subnet_ids" {
  description = "List of subnet IDs for VPC configuration"
  type        = list(string)
  default     = []
}

variable "vpc_security_group_ids" {
  description = "List of security group IDs for VPC configuration"
  type        = list(string)
  default     = []
}



variable "idp_common_layer_arn" {
  description = "ARN of the IDP common Lambda layer containing shared utilities"
  type        = string
}

variable "classification_model_id" {
  description = "Optional model ID for document classification. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "classification_max_workers" {
  description = "The maximum number of concurrent workers for document classification"
  type        = number
  default     = 20
}

variable "max_pages_for_classification" {
  description = "Maximum number of pages to use for classification. Set to 'ALL' to use all pages, or a numeric value to limit."
  type        = string
  default     = "ALL"

  validation {
    condition     = var.max_pages_for_classification == "ALL" || can(tonumber(var.max_pages_for_classification))
    error_message = "max_pages_for_classification must be 'ALL' or a numeric value."
  }
}

variable "classification_guardrail" {
  description = "Optional Bedrock guardrail to apply to classification model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "extraction_model_id" {
  description = "Optional model ID for information extraction. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "extraction_guardrail" {
  description = "Optional Bedrock guardrail to apply to extraction model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "ocr_max_workers" {
  description = "The maximum number of concurrent workers for OCR processing"
  type        = number
  default     = 20
}

variable "evaluation_enabled" {
  description = "Controls whether extraction results are evaluated for accuracy"
  type        = bool
  default     = false
}

variable "evaluation_model_id" {
  description = "Optional model ID for evaluating extraction results. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "is_summarization_enabled" {
  description = "Controls whether document summarization is enabled"
  type        = bool
  default     = false
}

variable "summarization_model_id" {
  description = "Optional model ID for document summarization. If not provided, the model from config.yaml will be used."
  type        = string
  default     = null
}

variable "summarization_guardrail" {
  description = "Optional Bedrock guardrail to apply to summarization model interactions"
  type = object({
    guardrail_id  = string
    guardrail_arn = string
  })
  default = null
}

variable "max_processing_concurrency" {
  description = "Maximum number of concurrent document processing tasks"
  type        = number
  default     = 100
}

variable "config" {
  description = "Optional configuration values to override defaults from config.yaml"
  type        = any
  default     = null
}



variable "enable_hitl" {
  description = "Whether to enable Human-in-the-Loop (HITL) functionality for document review"
  type        = bool
  default     = false
}

variable "assessment_model_id" {
  description = "The Bedrock model ID to use for assessment (when assessment is enabled)"
  type        = string
  default     = null
}

variable "assessment_guardrail" {
  description = "Optional Bedrock guardrail configuration for assessment model interactions"
  type = object({
    guardrail_id      = string
    guardrail_version = string
  })
  default = null
}

variable "lambda_tracing_mode" {
  description = "X-Ray tracing mode for Lambda functions. Valid values: Active, PassThrough"
  type        = string
  default     = "Active"
}

variable "tags" {
  description = "A map of tags to add to all resources"
  type        = map(string)
  default     = {}
}
