# Copyright Amazon.com, Inc. or its affiliates. All rights reserved.
# SPDX-License-Identifier: Apache-2.0
#
variable "region" {
  description = "AWS region to deploy resources"
  type        = string
  default     = "us-east-1"
}

variable "prefix" {
  description = "Prefix to add to resource names"
  type        = string
  default     = "idp"
}

# User Identity Configuration
variable "admin_email" {
  description = "Optional email address for the admin user. If provided, an admin user will be created in the Cognito User Pool."
  type        = string
  default     = null
}

variable "log_level" {
  description = "The log level for the document processing components"
  type        = string
  default     = "INFO"
  validation {
    condition     = contains(["DEBUG", "INFO", "WARNING", "ERROR", "CRITICAL"], var.log_level)
    error_message = "Allowed values for log_level are \"DEBUG\", \"INFO\", \"WARNING\", \"ERROR\", or \"CRITICAL\"."
  }
}

variable "log_retention_days" {
  description = "The retention period for CloudWatch logs generated by the document processing components in days"
  type        = number
  default     = 7
  validation {
    condition     = contains([1, 3, 5, 7, 14, 30, 60, 90, 120, 150, 180, 365, 400, 545, 731, 1827, 3653], var.log_retention_days)
    error_message = "Log retention days must be one of the allowed values."
  }
}

variable "data_tracking_retention_days" {
  description = "The retention period for document tracking data in days"
  type        = number
  default     = 365
}

# Feature flags
variable "enable_api" {
  description = "Enable GraphQL API for programmatic access and notifications"
  type        = bool
  default     = true
}

variable "web_ui" {
  description = "Web UI configuration object"
  type = object({
    enabled                    = optional(bool, true)
    create_infrastructure      = optional(bool, true)
    bucket_name                = optional(string, null)
    cloudfront_distribution_id = optional(string, null)
    logging_enabled            = optional(bool, false)
    logging_bucket_arn         = optional(string, null)
    enable_signup              = optional(string, "")
  })
  default = {
    enabled                    = true
    create_infrastructure      = true
    bucket_name                = null
    cloudfront_distribution_id = null
    logging_enabled            = false
    logging_bucket_arn         = null
    enable_signup              = ""
  }
}

# Evaluation Configuration
variable "enable_evaluation" {
  description = "Enable evaluation functionality (simplified flag)"
  type        = bool
  default     = false
}

variable "evaluation_model_id" {
  description = "Model ID for evaluation processing"
  type        = string
  default     = "anthropic.claude-3-sonnet-20240229-v1:0"
}

# Assessment Configuration
variable "enable_assessment" {
  description = "Enable assessment functionality for document quality assessment"
  type        = bool
  default     = false
}

# Reporting Configuration
variable "enable_reporting" {
  description = "Enable reporting functionality (simplified flag)"
  type        = bool
  default     = false
}

# Agent Analytics Configuration
variable "agent_analytics" {
  description = "Configuration for agent analytics functionality"
  type = object({
    enabled  = optional(bool, false)
    model_id = optional(string, "us.anthropic.claude-3-5-sonnet-20241022-v2:0")
  })
  default = { enabled = false }

  validation {
    condition     = !var.agent_analytics.enabled || var.agent_analytics.model_id != null
    error_message = "When agent_analytics.enabled is true, model_id must be provided."
  }
}

# Discovery Configuration
variable "discovery" {
  description = "Configuration for document discovery functionality"
  type = object({
    enabled = optional(bool, false)
  })
  default = { enabled = false }
}

# Chat with Document Configuration
variable "chat_with_document" {
  description = "Configuration for chat with document functionality"
  type = object({
    enabled                  = optional(bool, false)
    guardrail_id_and_version = optional(string, null)
  })
  default = { enabled = false }
}

# Process Changes Configuration
variable "process_changes" {
  description = "Configuration for document editing and reprocessing functionality"
  type = object({
    enabled = optional(bool, false)
  })
  default = { enabled = false }
}

# SageMaker Model Training Configuration
variable "training_config" {
  description = "Configuration for SageMaker model training"
  type = object({
    max_epochs    = optional(number, 3)
    base_model    = optional(string, "microsoft/udop-large")
    retrain_model = optional(bool, false)
  })
  default = {
    max_epochs    = 3
    base_model    = "microsoft/udop-large"
    retrain_model = false
  }
}

# SageMaker Configuration
variable "sagemaker_endpoint_name" {
  description = "Name of the SageMaker endpoint for UDOP processing (SageMaker UDOP processor only)"
  type        = string
  default     = "udop-endpoint"
}

# SageMaker Classifier Configuration
variable "classifier_instance_type" {
  description = "SageMaker instance type for the classifier endpoint"
  type        = string
  default     = "ml.g4dn.xlarge"
}

variable "classifier_min_instance_count" {
  description = "Minimum number of instances for the classifier endpoint"
  type        = number
  default     = 1
}

variable "classifier_max_instance_count" {
  description = "Maximum number of instances for the classifier endpoint"
  type        = number
  default     = 4
}

variable "classifier_target_invocations_per_instance_per_minute" {
  description = "Target invocations per instance per minute for classifier scaling"
  type        = number
  default     = 20
}

variable "classifier_scale_in_cooldown_seconds" {
  description = "Cooldown period after scaling in (seconds) for classifier"
  type        = number
  default     = 300
}

variable "classifier_scale_out_cooldown_seconds" {
  description = "Cooldown period after scaling out (seconds) for classifier"
  type        = number
  default     = 60
}

variable "encryption_key_arn" {
  description = "ARN of the KMS key for encryption (will be created if not provided)"
  type        = string
  default     = null
}

# Summarization Configuration
variable "summarization_enabled" {
  description = "Enable document summarization for SageMaker UDOP processor"
  type        = bool
  default     = true
}

variable "summarization_model_id" {
  description = "Model ID for document summarization (SageMaker UDOP processor)"
  type        = string
  default     = "us.anthropic.claude-3-5-sonnet-20241022-v2:0"
}

# Configuration File Path
variable "config_file_path" {
  description = "Path to the configuration YAML file for document processing"
  type        = string
  default     = "../../sources/config_library/pattern-3/rvl-cdip-package-sample/config.yaml"
}

variable "tags" {
  description = "Tags to apply to all resources"
  type        = map(string)
  default     = {}
}

variable "force_rebuild_layers" {
  description = "Force rebuild of Lambda layers regardless of requirements changes"
  type        = bool
  default     = false
}
