version: 0.2

phases:
  pre_build:
    commands:
      - echo ${SOURCE_CODE_LOCATION}
      - echo Installing NodeJS 22
      - n 22.14.0
      - node --version
      - npm --version
      - echo Installing Web UI dependencies
      - npm ci
  build:
    commands:
      - echo Build started on `date`
      - cd $CODEBUILD_SRC_DIR
      - echo Building Web UI
      - npm run build
      - printf '{"RepositoryUri":"%s","ProjectName":"%s","ArtifactBucket":"%s"}' $REPOSITORY_URI $PROJECT_NAME $ARTIFACT_BUCKET > build.json
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Copying Web UI
      - find dist -ls
      - aws s3 cp --recursive dist s3://${WEBAPP_BUCKET}/
      - |
        if [ -n "$CLOUDFRONT_DISTRIBUTION_ID" ] && [ "$CLOUDFRONT_DISTRIBUTION_ID" != "" ]; then
          echo "Invalidating CloudFront Distribution: $CLOUDFRONT_DISTRIBUTION_ID"
          aws cloudfront create-invalidation --distribution-id "$CLOUDFRONT_DISTRIBUTION_ID" --paths '/*'
        else
          echo "No CloudFront distribution ID provided, skipping cache invalidation"
        fi

artifacts:
  files:
    - build.json
